export enum AndamentoPedido {
  AGUARDANDO_PAGAMENTO = 'AGUARDANDO_PAGAMENTO',

  CANCELADO = 'CANCELADO',

  ESTORNADO = 'ESTORNADO',

  ENTREGUE = 'ENTREGUE',

  PEDIDO = 'PEDIDO',

  PAGO = 'PAGO',
}
